# Generated by Django 2.2.6 on 2019-10-15 13:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_auto_20191015_1149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dateactive',
            managers=[
                ('livedates', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='mobile',
            field=models.CharField(max_length=13, verbose_name='Phone Number'),
        ),
    ]
