# Generated by Django 2.2.6 on 2019-10-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_auto_20191015_1446'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dateactive',
            managers=[
            ],
        ),
    ]
