# Generated by Django 2.2.6 on 2019-12-10 09:35

from django.db import migrations, models
import django.db.models.deletion
import laboratory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=13, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Member',
            },
        ),
        migrations.CreateModel(
            name='DateActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=1)),
                ('startdate', models.DateTimeField(default=laboratory.models.DateActive.default_start_time, max_length=250)),
                ('enddate', models.DateTimeField(default=laboratory.models.DateActive.default_end_time, max_length=250)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Members')),
            ],
            options={
                'verbose_name': 'Active Date',
            },
        ),
    ]
