# Generated by Django 2.2.7 on 2019-12-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_auto_20191210_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateactive',
            name='deskphone',
        ),
    ]
